---
sudo: false
addons:
  apt:
    packages:
      - aspell
      - aspell-en
language: perl
perl:
  - blead
  - dev
  - '5.22'
  - '5.20'
  - '5.18'
  - '5.16'
  - '5.14'
  - '5.12'
  - '5.10'
matrix:
  allow_failures:
    - perl: blead
  include:
    - env: COVERAGE=1
      perl: '5.22'
env:
  global:
    - RELEASE_TESTING=1
    - AUTHOR_TESTING=1
before_install:
  - eval $(curl https://travis-perl.github.io/init) --auto
notifications:
  email:
    on_failure: always
    on_success: change
    recipients:
      - dev-ci@maxmind.com
  slack:
    rooms:
      secure: "oNGxkGgpzh2Co5AJRzL/SR6+YF1FiKLJ+p74ucadCErdQGiCqzfYZu3RwLBdj+xErpofSfHm8GfSheztKJsSb84HiaqRs+xqBITE/VGCjY6zlslj7sa+acHYGZzTxZFI52UTRP6h+VMSF2oUUmbRwOk1Jku1WHv4mMQ//spW6GQLYgScVkLIeqMTopKOFejGtQSlJwN8fqB7E0Nk1lFebo3B9UZtdXuGamfWlDuq+6UdGF4WuXxicWZUhyYovDXP4eHoBZNB7mBgYmM7FvgyS+7VefH561TZq5Yx9zUd+UG22EJBKlRcTUog160UPO97+k46C97DeQVGbX76sh7s5OLCpZA3M0/l/JtKMGkeO5HXajN62pZsfxKuLJ7QWUSMRMrEFt6/HrIxFn8ZB8kHtfD8O96NxCMfJ28zzQMblpp4X100UyYNGza1ovg5cxwnbqCrHHu0R5LJ/3sMaevDtQR/eW24AOlPOGNgy4RSnOLnaG8QAI3zv85Dv7LVQspVK3hFlRW5KUH3aL7PgF7RgUE/weKiXEkH8UNuKbZLl0zEY3V5FinqjdWw8p+FZnJfWN8ajx6eyaDQa1sO+51k4yAhfgJZ+yIPpGY1NKD8Koi0L6beEtCpZNFtFltPq53fDHHBSPSEU+tT9XbwWp8aRShI934e/xpsiFB2Vr8Ms0E=\n"
